package vista;

import controlador.ControladorCRUDEstudiantes;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ArchivoOrgnDir;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

public class VistaCRUDEstudiantes extends javax.swing.JFrame {
    ControladorCRUDEstudiantes objControladorCRUDEst;
    ArchivoOrgnDir objArchivo; // Pertenece a modelo

    public VistaCRUDEstudiantes() {
        initComponents();
        cargarDatosEnTabla();
        this.objArchivo = new ArchivoOrgnDir();
        this.objControladorCRUDEst = new ControladorCRUDEstudiantes(this, this.objArchivo);
        // this.objControladorCRUDEst.llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumControlBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEstudiantes = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Estudiantes");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tecnológico del Valle de Oaxaca");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Agenda de Estudiantes");

        txtNumControlBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumControlBuscarKeyPressed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar232px.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        jtblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "Num. Control", "Nombre", "Apellidos", "Semestre", "Grupo", "Carrera"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblEstudiantes);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar48px.png"))); // NOI18N
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar48px.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar48px.png"))); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addComponent(jLabel2)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAgregar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnEliminar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEditar))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 25, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtNumControlBuscar,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 116,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnBuscar))
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 536,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnBuscar)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(txtNumControlBuscar,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAgregar)
                                        .addComponent(btnEliminar)
                                        .addComponent(btnEditar))
                                .addContainerGap(58, Short.MAX_VALUE)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        FrmEditarEstudiante objEditarEstudiante = new FrmEditarEstudiante(this.objControladorCRUDEst);
        objEditarEstudiante.setVisible(true);
    }// GEN-LAST:event_btnEditarMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        FrmAgregarEstudiante objAgregarEstudiante = new FrmAgregarEstudiante(this.objControladorCRUDEst);
        objAgregarEstudiante.setVisible(true);
    }// GEN-LAST:event_btnAgregarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        FrmEliminarEstudiante objEliminarEstudiante = new FrmEliminarEstudiante(this.objControladorCRUDEst);
        objEliminarEstudiante.setVisible(true);
    }// GEN-LAST:event_btnEliminarMouseClicked

    private void txtNumControlBuscarKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNumControlBuscarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            this.buscar();
    }// GEN-LAST:event_txtNumControlBuscarKeyPressed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        this.buscar();
    }// GEN-LAST:event_btnBuscarMouseClicked

    // Metodo 2 de buscar y seleccionar en el JTable un registro
    private void buscar() {
        String numControlBus = this.txtNumControlBuscar.getText();
        // this.objControladorCRUDEst.buscarSeleccionarRegistro(numControlBus);
        /*
         * String registro[] = this.objControladorCRUDEst.buscarRegistro(numControlBus);
         * int fila = Integer.parseInt(registro[6]);
         * if(registro!=null){
         * DefaultTableModel modelo = (DefaultTableModel)
         * this.jtblEstudiantes.getModel();
         * this.jtblEstudiantes.setRowSelectionInterval(fila, fila);
         * this.jtblEstudiantes.setSelectionBackground(Color.BLUE);
         * }
         * else
         * JOptionPane.showMessageDialog(this,"El registro no Existe");
         * /*if (registro!=null){
         * DefaultTableModel modelo = (DefaultTableModel)
         * this.jtblEstudiantes.getModel();
         * for(int i=0; i<modelo.getRowCount(); i++ ){
         * String nControl = modelo.getValueAt(i, 0).toString();
         * if(nControl.equals(numControlBus)){
         * this.jtblEstudiantes.setRowSelectionInterval(i, i);
         * this.jtblEstudiantes.setSelectionBackground(Color.BLUE);
         * }
         * }
         * }
         * else
         * JOptionPane.showMessageDialog(this,"El registro no Existe");
         */
        // Verificar que se ingresó un número de control
        if (numControlBus.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un número de control",
                    "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) this.jtblEstudiantes.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        this.jtblEstudiantes.setRowSorter(sorter);

        if (numControlBus.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            // Filtrar para mostrar solo el estudiante con el número de control buscado
            sorter.setRowFilter(RowFilter.regexFilter("^" + numControlBus + "$", 0));
        }

        // Si hay filas visibles después del filtrado, seleccionar la primera
        if (this.jtblEstudiantes.getRowCount() > 0) {
            this.jtblEstudiantes.setRowSelectionInterval(0, 0);
            this.jtblEstudiantes.setSelectionBackground(Color.GREEN);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún estudiante con ese número de control",
                    "No encontrado", JOptionPane.INFORMATION_MESSAGE);
            // Quitar el filtro para mostrar todos los registros nuevamente
            sorter.setRowFilter(null);
        }
    }

    // En la clase VistaCRUDEstudiantes
    private void cargarDatosEnTabla() {
        // Crear instancia de ArchivoOrgnDir
        ArchivoOrgnDir archivo = new ArchivoOrgnDir();

        // Abrir el archivo
        archivo.abrirArchivoRAF("estudiantes.dat");

        // Leer todos los registros
        Object[][] datos = archivo.leerTodosLosRegistros();

        // Definir los nombres de las columnas
        String[] columnas = { "Núm. Control", "Nombre", "Apellidos", "Semestre", "Grupo", "Carrera" };

        // Crear modelo de tabla con los datos y columnas
        DefaultTableModel modelo = new DefaultTableModel(datos, columnas);

        // Asignar el modelo a la tabla
        jtblEstudiantes.setModel(modelo);

        // Cerrar el archivo
        // archivo.cerrarArchivo();
    }

    public void actualizarTabla() {
        cargarDatosEnTabla();
    }
    // Llamar al método en el constructor o en un método de inicialización

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCRUDEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCRUDEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCRUDEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCRUDEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCRUDEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtblEstudiantes;
    private javax.swing.JTextField txtNumControlBuscar;
    // End of variables declaration//GEN-END:variables
}